# CircleCI Firebase Deployment Config
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
  aws-ecr: circleci/aws-ecr@8.0.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          region: ${AWS_DEFAULT_REGION}
          tag: ${CIRCLE_BRANCH}
          push-image: true
          executor: aws-ecr/default
          public-registry: false
          registry-id: AWS_ACCOUNT_ID
          filters:
            branches:
              only:
                - dev
                - main