# CircleCI Firebase Deployment Config
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
  aws-ecr: circleci/aws-ecr@0.0.2

jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: python --version

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            branches:
              only: 
              - dev-uvi
              # - main