# CircleCI Firebase Deployment Config
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2

jobs:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"

workflows:
  version: 2
  build_all:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: 
              - dev-uvicorn
              # - main