name: mypy

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # this is failing
      # - uses: jpetrucciani/mypy-check@master
      #   with:
      #     mypy_flags: '--install-types --non-interactive'
      #     path: lnbits
